;; This theme was originally implemented as twilight but I customized it...

(defun color-theme-mytwilight ()
  "Color theme by Marcus Crafter, based off the TextMate Twilight theme, created 2008-04-18. Changed by Martin Stoev"
  (interactive)
  (color-theme-install
   '(color-theme-mytwilight
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "black" :foreground "white"))))
     (blue ((t (:foreground "blue"))))
     (mode-line ((t (:background "#2b2b2b" :foreground "white" :box (:line-width 1 :style none)))))
     (modeline-buffer-id ((t (:bold t :background "#2b2b2b" :foreground "#dfdfdf" ))))
     (modeline-mousable ((t (:background "#2b2b2b"  :foreground "#dfdfdf"))))
     (modeline-mousable-minor-mode ((t (:background "#2b2b2b" :foreground "#dfdfdf"))))
     (italic ((t (:italic t))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (underline ((t (:underline t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (font-lock-builtin-face ((t (:foreground "white"))))
     (font-lock-comment-face ((t (:italic t :foreground "#9556af"))))
     (font-lock-constant-face ((t (:foreground "#CF6A4C"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#9B703F"))))
     (font-lock-keyword-face ((t (:foreground "#CDA869"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))

     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))

     (font-lock-string-face ((t (:foreground "#8F9D6A"))))
     (font-lock-type-face ((t (:foreground "#9B703F"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (region ((t (:background "#27292A"))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (minibuffer-prompt ((t (:foreground "white"))))
     (isearch ((t (:foreground "#ebe494" :background "#d48085" ))))
     (isearch-lazy-highlight-face ((t (:foreground "#d48085" :background "#ebe494" ))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))